language: node_js

node_js:
  - 6
  - 8
  - 9

script:
  - npm run lint
  - npm test

after_success:
  - npm run cover

deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    on:
      tags: true
